### ISSUE TITLE
Fighting from inside a Trader

### ISSUE THREAD

**Issue by das-nervt** [arramus/A21-Preppocalypse#3]
Hello, thx for the great expeirence!
I found a Issue that hang the Game if I try to fight from inside a Trader until I move backwards far enough.
(playing on Steam/linux)

**Comment by arramus** [comment]
Hello, and thank you for the feedback.

None of the Traders have been changed in any way from the original game traders. There is one additional Trader in the Old West, Prepper Trader Bob, but he also matches original game traders and complies with the required A21 settings. A21 still has many small issues still and this is the first I've heard of this one. It could potentially be an issue specific to the Steam/Linux setup if it's consistent and repeatable. It also helps to share a game log when reporting issues as it allows to check for any warnings or errors.

If it's only happening while using Preppocalypse, and not happening at all when using no Mods or other Mods, then things point towards Preppocalypse not properly hooking up with the Steam/Linus setup. It is best to visit the main 7 Days forum and discuss such issues with other gamers who are also using the same Steam/Linux setup since they will be able to verify it or not. This is not something I am able to assist with or verify since I am not on the Steam/Linux platform.

There really is not a lot of Steam/Linux discussion and very few bug reports on the main 7D2D forum. There are only 4 Known Issues related to Linux in the official [list](https://docs.google.com/spreadsheets/d/13VnmkOdKC9XEOy_neb0Tp34-WPXu-aDw4jfJxcquuvc/edit#gid=0). https://community.7daystodie.com/a21-bugs-main/linux-under-review/
